hl.on("hyprland.start", function()
  hl.exec_cmd("noctalia")
  hl.exec_cmd("systemctl --user start polkit-gnome-authentication-agent-1")
  hl.exec_cmd("wl-clip-persist --clipboard regular --reconnect-tries 0")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("zen-beta")
  hl.exec_cmd("vesktop")
  hl.exec_cmd("spotify")
  hl.exec_cmd("matugen-apply")
  hl.exec_cmd("openrgb-wooting-sync --watch")
end)
