# SDDM Chili Theme Customization
# Generated automatically by Matugen from wallpaper
[General]
background = "/home/tiizzel/Pictures/wallhaven-0w2xpq.jpg"
blur = false
recursiveBlur = false
showSessionsByDefault = true
showUsersByDefault = true
fontSize = 11
font = "JetBrainsMono Nerd Font"
