color0 #444650
color1 #ffb4ab
color2 #b3c5ff
color3 #bfc6e2
color4 #efb3ef
color5 #b3c5ff
color6 #bfc6e2
color7 #e3e2e7
color8 #8f909b
color9 #ffb4ab
color10 #b3c5ff
color11 #bfc6e2
color12 #efb3ef
color13 #b3c5ff
color14 #bfc6e2
color15 #e3e2e7

cursor                #e3e2e7
cursor_text_color     #121317
background            #121317
foreground            #e3e2e7
selection_foreground  #c5c6d1
selection_background  #444650
active_border_color   #b3c5ff
inactive_border_color #444650
url_color             #b3c5ff

active_tab_foreground   #152d65
active_tab_background   #b3c5ff
inactive_tab_foreground #c5c6d1
inactive_tab_background #444650
cursor_trail_color      #c5c6d1
