color0 #56433c
color1 #ffb4ab
color2 #ffb599
color3 #f6b8a1
color4 #d0cb50
color5 #ffb599
color6 #f6b8a1
color7 #f1dfd9
color8 #a48c83
color9 #ffb4ab
color10 #ffb599
color11 #f6b8a1
color12 #d0cb50
color13 #ffb599
color14 #f6b8a1
color15 #f1dfd9

cursor                #f1dfd9
cursor_text_color     #1a110e
background            #1a110e
foreground            #f1dfd9
selection_foreground  #dcc1b7
selection_background  #56433c
active_border_color   #ffb599
inactive_border_color #56433c
url_color             #ffb599

active_tab_foreground   #5a1c00
active_tab_background   #ffb599
inactive_tab_foreground #dcc1b7
inactive_tab_background #56433c
cursor_trail_color      #dcc1b7
