color0 #524436
color1 #ffb4ab
color2 #ffc688
color3 #ebbe8f
color4 #cbd966
color5 #ffb868
color6 #ebbe8f
color7 #eee0d4
color8 #a08e7d
color9 #ffb4ab
color10 #ffc688
color11 #ebbe8f
color12 #cbd966
color13 #ffb868
color14 #ebbe8f
color15 #eee0d4

cursor                #eee0d4
cursor_text_color     #19120c
background            #19120c
foreground            #eee0d4
selection_foreground  #d7c3b0
selection_background  #524436
active_border_color   #ffc688
inactive_border_color #524436
url_color             #ffc688

active_tab_foreground   #482900
active_tab_background   #ffc688
inactive_tab_foreground #d7c3b0
inactive_tab_background #524436
cursor_trail_color      #d7c3b0
