# Fallback colors for MangoWM window borders and decoration
# Generated automatically by Matugen from wallpaper
rootcolor = 0x11140eff
bordercolor = 0x8e9285ff
focuscolor = 0xafd18cff
maximizescreencolor = 0xafd18cff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xbfcbaeff
globalcolor = 0xa0cfcdff
overlaycolor = 0x33362eff
