# Fallback colors for MangoWM window borders and decoration
# Generated automatically by Matugen from wallpaper
rootcolor = 0x151217ff
bordercolor = 0x968e98ff
focuscolor = 0xdbb9f9ff
maximizescreencolor = 0xdbb9f9ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd1c1d9ff
globalcolor = 0xf3b7bdff
overlaycolor = 0x373339ff
