# Fallback colors for MangoWM window borders and decoration
# Generated automatically by Matugen from wallpaper
rootcolor = 0x1a110eff
bordercolor = 0xa08d86ff
focuscolor = 0xffb599ff
maximizescreencolor = 0xffb599ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe7beafff
globalcolor = 0xd4c78eff
overlaycolor = 0x3d322fff
