# | Input Devices |
# Configure your input devices here | https://mangowm.github.io/docs/configuration/input

# Keyboard layout
xkb_rules_layout = de

# Keyboard repeat rate and delay
repeat_rate = 25
repeat_delay = 600
numlockon = 0

# Trackpad
disable_trackpad = 0
tap_to_click = 1
tap_and_drag = 1
drag_lock = 1
trackpad_natural_scrolling = 1
trackpad_disable_while_typing = 1
trackpad_left_handed = 0
trackpad_middle_button_emulation = 0
swipe_min_threshold = 1

# Mouse
mouse_natural_scrolling = 0
