# | Miscellaneous Settings |
# Documentation: https://mangowm.github.io/docs/configuration/miscellaneous

allow_tearing = 2
syncobj_enable = 1
drag_tile_to_tile = 1

focus_on_activate = 1
sloppyfocus = 1
warpcursor = 1
focus_cross_monitor = 0
focusdir_only_zone_overlap = 1
enable_floating_snap = 0
snap_distance = 30
