# MangoWM Main Configuration File
# Documentation: https://mangowm.github.io/docs/quick-start
# Noctalia Integration: https://docs.noctalia.dev/noctalia/compositor-settings/mango/

# ============= MODULAR CONFIGS =============
# Colors and Noctalia Theme
source-optional = ./noctalia.conf
source-optional = ./cfg/colors.conf

# Hardware and Display
source = ./cfg/monitors.conf
source = ./cfg/env.conf
source = ./cfg/input.conf

# Look and Feel (tuned for Noctalia)
source = ./cfg/appearance.conf

# Window Layouts and Rules
source = ./cfg/layout.conf
source = ./cfg/rules.conf

# Autostart and Keybindings
source = ./cfg/autostart.conf
source = ./cfg/keybinds.conf

# Miscellaneous Settings
source = ./cfg/misc.conf
