# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x121314ff
bordercolor = 0x8c9294ff
dropcolor = 0xb3cad380
splitcolor = 0xd0c1d9ff
focuscolor = 0xb3cad3ff
maximizescreencolor = 0xbfc8ccff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd0c1d9ff
globalcolor = 0x596f77ff
overlaycolor = 0x424a4eff
jump_label_decorate_fg_color = 0xe3e2e2ff
jump_label_decorate_bg_color = 0x292a2bff
jump_label_decorate_focus_fg_color = 0x1e333bff
jump_label_decorate_focus_bg_color = 0xb3cad3ff
jump_label_decorate_border_color = 0x8c9294ff
group_bar_decorate_fg_color = 0xe3e2e2ff
group_bar_decorate_bg_color = 0x292a2bff
group_bar_decorate_focus_fg_color = 0x1e333bff
group_bar_decorate_focus_bg_color = 0xb3cad3ff
group_bar_decorate_border_color = 0x8c9294ff
