# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x111319ff
bordercolor = 0x8c919dff
dropcolor = 0xa9c7ff80
splitcolor = 0xf6adffff
focuscolor = 0xa9c7ffff
maximizescreencolor = 0xb4c7edff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xf6adffff
globalcolor = 0x6098edff
overlaycolor = 0x344767ff
jump_label_decorate_fg_color = 0xe1e2e9ff
jump_label_decorate_bg_color = 0x282a30ff
jump_label_decorate_focus_fg_color = 0x003062ff
jump_label_decorate_focus_bg_color = 0xa9c7ffff
jump_label_decorate_border_color = 0x8c919dff
group_bar_decorate_fg_color = 0xe1e2e9ff
group_bar_decorate_bg_color = 0x282a30ff
group_bar_decorate_focus_fg_color = 0x003062ff
group_bar_decorate_focus_bg_color = 0xa9c7ffff
group_bar_decorate_border_color = 0x8c919dff
