# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x19120cff
bordercolor = 0xa08e7dff
dropcolor = 0xffc68880
splitcolor = 0xcbd966ff
focuscolor = 0xffc688ff
maximizescreencolor = 0xebbe8fff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xcbd966ff
globalcolor = 0xf4a441ff
overlaycolor = 0x62431eff
jump_label_decorate_fg_color = 0xeee0d4ff
jump_label_decorate_bg_color = 0x302921ff
jump_label_decorate_focus_fg_color = 0x482900ff
jump_label_decorate_focus_bg_color = 0xffc688ff
jump_label_decorate_border_color = 0xa08e7dff
group_bar_decorate_fg_color = 0xeee0d4ff
group_bar_decorate_bg_color = 0x302921ff
group_bar_decorate_focus_fg_color = 0x482900ff
group_bar_decorate_focus_bg_color = 0xffc688ff
group_bar_decorate_border_color = 0xa08e7dff
